### ISSUE TITLE
An error while using useProductFruits hook

### ISSUE THREAD

**Issue by nsinotov** [product-fruits/react-product-fruits#2]
Hello Product Fruits team.

I'm using the last version 1.4.8 at the moment and have an error while using the `useProductFruits` hook. The `window.productFruits` is undefined at the same time as when `window.productFruitsIsReady` equals true.

![Screenshot 2022-08-25 at 12 42 44](https://user-images.githubusercontent.com/17026961/186636836-a4864b91-264a-46d4-bf49-7413a573d21b.png)

**Comment by ladislavsalom** [comment]
Hello  @nsinotov,

please update to 1.4.9, there should be a fix.
