### ISSUE TITLE
Critical bug in Firefox: infinite attempt to reconnect after the component re-mount

### ISSUE THREAD

**Issue by vladminsky** [product-fruits/react-product-fruits#3]
Hi team,

I experience infinite attempt to reconnect after the component re-mount in Firefox (106.0.2). This leads to browser unresponsiveness in some cases.
In Chrome and Safari works fine.

What I tried:
- I upgraded to version 2.0.1 (the issue persists)
- I tried dontDestroy property (https://help.productfruits.com/en/article/developers-integration-react-nextjs#4.-use-the-component)  - still don’t help (and I doubt it works at all actually).

Seems like an urgent issue. Can you fix please?

Thanks in advance.

**Comment by ladislavsalom** [comment]
Hello @vladminsky ,

thanks for reporting. I believe we were able to fix the issue. You don't have to update the version in your app, as the fix was applied in the PF runtime code.

If the issue still persists, please connect with us on our chat or at support(at)productfruits.com.

Ladislav

**Comment by vladminsky** [comment]
It is fixed. Thank you for quick reaction.
