### ISSUE TITLE
Source maps are invalid in npm package

### ISSUE THREAD

**Issue by adamandreasson** [product-fruits/react-product-fruits#4]
Using version 2.2.3

I get errors in my console

```
WARNING in ./node_modules/react-product-fruits/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/.../node_modules/react-product-fruits/src/hooks.ts' file: Error: ENOENT: no such file or directory, open '/.../node_modules/react-product-fruits/src/hooks.ts'
```

The sourcemaps in the package contain references to a `hooks.js ` which does not exist in the dist folder.

We have temporarily solved this by using the contents in this repository instead of npm, but it's obviously not a good fix.

**Comment by fredrbl** [comment]
+1, I get the same compilation warning. Thanks for the suggested work around @adamandreasson, will implement this as well. But obviously not a sustainable solution

**Comment by ladislavsalom** [comment]
Thanks for the report @adamandreasson @fredrbl 

We were not able to reproduce it in our environment, however, we tried to publish a fix that could fix this issue. You can try to upgrade to **2.2.4**.

If the issue still persists, can you please share your React version, or if you use CRA, then the CRA version? Thanks

**Comment by adamandreasson** [comment]
We installed 2.2.4 and can confirm this version fixed the bug for us. Thanks.
