### ISSUE TITLE
React + NextJS: pageChanged does not exist on productFruits object.

### ISSUE THREAD

**Issue by iantbutler01** [product-fruits/react-product-fruits#9]
Hey useful product! One thing when following this example:

```
import Router from 'next/router'

Router.events.on('routeChangeComplete', () => {
    window.productFruits.pageChanged();
});

// Here comes the App component function
//function App({ Component, pageProps }: AppProps) {
```

from https://help.productfruits.com/en/article/developers-integration-react-nextjs

pageChanged() doesn't exist as a function and searching the code in this repo it doesn't seem to exist at all.

**Comment by ladislavsalom** [comment]
Hi @iantbutler01, this function exists but is loaded when PF scripts are downloaded from our servers. It is not a function embedded in this SDK.

If you use TypeScript, you might have to add types manually to the `productFruits` window object based on what you want to call from it.

If it is undefined, then PF is probably not loaded and you have to check it according to this page: https://help.productfruits.com/en/article/javascript-api-overview
